backend = "glx";
vsync = true;


inactive-dim = 0.2; 

focus-exclude = [
    "focused",
#    "group_focused",
    "class_g = 'i3bar'",
    "class_g = 'Vlc'",
    "class_g = 'vlc'",
#    "window_type = 'desktop'"
];


fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 4;

fade-exclude = [ 
    "class_g = 'py3status'"
];


corner-radius = 10;
round-borders = 1;

rounded-corners-exclude = [
  "class_g = 'dmenu'",
  "class_g = 'i3bar'",
];

#################################
# General Settings
#################################
detect-rounded-corners = true;
detect-client-opacity = true;

# Crucial for i3 to report focus correctly across monitors
use-ewmh-active-win = true; 

wintypes:
{
    normal = { shadow = true; shadow-color = "#FF0000"; };
    tooltip = { fade = true; shadow = true; opacity = 1.0; focus = true; };
    menu = { fade = true; shadow = true; opacity = 1.0; focus = true; };
    dropdown_menu = { fade = true; shadow = true; opacity = 1.0; focus = true; };
    popup_menu = { fade = true; shadow = true; opacity = 1.0; focus = true; };
};
