#! /bin/bash

current_notes="a1-6.csv"
current_folder="/home/laotze/Downloads/A1.1/[TutsNode.com] - Best Way to Learn German Language-Full Beginner Course-A1.1/8. Unit 7 - Arbeiten und lernen (Working and learning)/"
last_lesson="39. 7.11. Jahre (Years).mp4"

cd "$current_folder"

nohup thunar . &
nohup mpv "$last_lesson" &

cd

nvim "./notes/german/$current_notes"
